enabled: true
http:
  routers:
    auto:
      rule: "Host(`auto.aeroponics.club`)"
      service: auto
      entrypoints:
      - websecure
      tls:
        certResolver: le

  services:
    auto:
      loadBalancer:
        servers:
        - url: "http://super1:3005/"
